[package]
name = "token"
type = "contract"
authors = ["gh0xt"]

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-nr", tag="v4.2.0", directory="aztec" }
compressed_string = { git="https://github.com/AztecProtocol/aztec-nr", tag="v4.2.0", directory="compressed-string" }
balance_set = { git="https://github.com/AztecProtocol/aztec-nr", tag="v4.2.0", directory="balance-set" }
caller_contract = { path = "../caller_contract" }
uint_note = { git="https://github.com/AztecProtocol/aztec-nr", tag="v4.2.0", directory="uint-note" }